from control_analysis.data import ControlDataBundle, EvalWindowGraphSpec, compute_control_ranks, df_enhance, load_control_bundle
from control_analysis.formatting import latex_tabular, print_latex, write_dataframe_tabular, write_latex_table
from control_analysis.jobs import (
    plot_dim_red_kind_ranking,
    plot_elapsed_time_by_dim_red_kind,
    plot_full_desc_ranking,
    plot_gp_dim_reduction,
    plot_gp_true_evaluations_by_population,
    plot_gp_true_ratio,
    plot_model_comparison,
    plot_pca_ratio_gp,
    plot_pure_population_size,
    render_eval_window_graph,
    run_doe_group_analysis,
    run_eval_window_graphs,
    run_named_plots,
    run_stats_report,
)
from control_analysis.models import ControlDataBundle, EvalWindowGraphSpec
from control_analysis.plotting import bar, save_and_show, set_default_baselines, two_layer_tics, xy_scatter
from control_analysis.stats import (
    ALPHA,
    DEFAULT_EQUIVALENCE_DELTA,
    DEFAULT_EQUIVALENCE_SWEEP,
    auc,
    compute_equivalence_test,
    compute_significance_summary,
    equivalence,
    export_significance_table,
    find_first_equivalent_margin,
    prepare_model_kind_comparison,
    stat_tests,
    sweep_equivalence_margins,
    write_stats_report,
)
from control_analysis.transforms import add_func_group, avg_axis0_rugged, close_to, default_groupby, get_param_desc_title, np_apply_axis0, p

__all__ = [
    "ControlDataBundle",
    "ALPHA",
    "DEFAULT_EQUIVALENCE_DELTA",
    "DEFAULT_EQUIVALENCE_SWEEP",
    "EvalWindowGraphSpec",
    "add_func_group",
    "auc",
    "avg_axis0_rugged",
    "bar",
    "close_to",
    "compute_control_ranks",
    "compute_equivalence_test",
    "compute_significance_summary",
    "default_groupby",
    "df_enhance",
    "equivalence",
    "export_significance_table",
    "find_first_equivalent_margin",
    "get_param_desc_title",
    "latex_tabular",
    "load_control_bundle",
    "np_apply_axis0",
    "p",
    "plot_dim_red_kind_ranking",
    "plot_elapsed_time_by_dim_red_kind",
    "plot_full_desc_ranking",
    "plot_gp_dim_reduction",
    "plot_gp_true_evaluations_by_population",
    "plot_gp_true_ratio",
    "plot_model_comparison",
    "plot_pca_ratio_gp",
    "plot_pure_population_size",
    "plot_true_ratio_ranking",
    "prepare_model_kind_comparison",
    "print_latex",
    "render_eval_window_graph",
    "run_doe_group_analysis",
    "run_eval_window_graphs",
    "run_named_plots",
    "run_stats_report",
    "save_and_show",
    "set_default_baselines",
    "stat_tests",
    "sweep_equivalence_margins",
    "two_layer_tics",
    "write_dataframe_tabular",
    "write_latex_table",
    "write_stats_report",
    "xy_scatter",
]
